services:
  src.purchase.ticket.domain.query_model.submit_ticket_needle_data_query:
    class: src.purchase.ticket.infrastructure.domain.query_model.sqlalchemy.sqlalchemy_submit_ticket_needle_data_query
    arguments:
      - "@src.shared.database.domain.connection.connection"

  src.purchase.ticket.domain.query_model.ticket_retriever_needle_data_query:
    class: src.purchase.ticket.infrastructure.domain.query_model.sqlalchemy.sqlalchemy_ticket_retriever_needle_data_query
    arguments:
      - "@src.shared.database.domain.connection.connection"

  src.purchase.ticket.domain.query_model.start_ticket_validation_needle_data_query:
    class: src.purchase.ticket.infrastructure.domain.query_model.sqlalchemy.sqlalchemy_start_ticket_validation_needle_data_query
    arguments:
      - "@src.shared.database.domain.connection.connection"

  src.purchase.ticket.domain.query_model.validate_ticket_needle_data_query:
    class: src.purchase.ticket.infrastructure.domain.query_model.sqlalchemy.sqlalchemy_validate_ticket_needle_data_query
    arguments:
      - "@src.shared.database.domain.connection.connection"

  src.purchase.ticket.domain.query_model.finish_ticket_validation_needle_data_query:
    class: src.purchase.ticket.infrastructure.domain.query_model.sqlalchemy.sqlalchemy_finish_ticket_validation_needle_data_query
    arguments:
      - "@src.shared.database.domain.connection.connection"