services:
    src.catalogue.format.application.command.change_equivalence_units_command_handler:
        class: src.catalogue.format.application.command.change_equivalence_units_command_handler
        arguments:
            - '@src.catalogue.format.domain.model.format_repository'
            - '@src.shared.cqrs.domain.service.message_publisher'
